version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sentiment-backend
    ports:
      - "3000:3000"
    environment:
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN}
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./:/app
      - /app/node_modules

  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: sentiment-frontend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
